# Generated by Django 4.0.1 on 2022-04-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameid', models.CharField(max_length=10)),
                ('player1', models.CharField(max_length=10)),
                ('player2', models.CharField(max_length=10)),
                ('turn', models.CharField(max_length=10)),
                ('box1', models.CharField(max_length=10)),
                ('box2', models.CharField(max_length=10)),
                ('box3', models.CharField(max_length=10)),
                ('box4', models.CharField(max_length=10)),
                ('box5', models.CharField(max_length=10)),
                ('box6', models.CharField(max_length=10)),
                ('box7', models.CharField(max_length=10)),
                ('box8', models.CharField(max_length=10)),
                ('box9', models.CharField(max_length=10)),
            ],
        ),
    ]
